languageCode = "en-us"
title = "Noah Dietz"
baseurl = "https://noahdietz.me/"
theme = "aerial"

[params]
  name = "Noah Dietz"
  about = "Software Engineer &nbsp;&bull;&nbsp; Sports fan &nbsp;&bull;&nbsp; Runner"
  copyright = "Noah Dietz"
  #Disable the scrolling background by entering any string for bg_scroll. Enable by leaving bg_scroll empty.
  bg_scroll = "off please"
  favicon = "favicon.ico"
  coffeeName = "Black Oak Coffee Roasters - Congo Kivu"
  coffeeLink = "https://blackoakcoffee.com/collections/single-origin-coffees/products/congo-kivu"
  currentlyAt = "Mountain View, CA"

[[params.social]]
  medium = "Twitter"
  icon = "twitter"
  link = "http://twitter.com/no_d_here"

[[params.social]]
  medium = "Instagram"
  icon = "instagram"
  link = "https://www.instagram.com/noah_dietz/"

[[params.social]]
  medium = "Github"
  icon = "github"
  link = "https://github.com/noahdietz"

